// Generated by flowstile codegen — do not edit manually.
// Source: http://localhost:3000  |  Process: Vacation Leave Request  |  2026-06-14
// Regenerate: flowstile-codegen --process "Vacation Leave Request" --task-queue flowstile

import { defineProcess } from '@flowstile/sdk/process';

// ---------------------------------------------------------------------------
// Form output types (typed submission data returned by createAndWait)
// ---------------------------------------------------------------------------

/** Form: VACATION_MANAGER_REVIEW (v1) */
export interface VacationManagerReviewOutput extends Record<string, unknown> {
  DAYS: number;
  NOTES?: string;
  REASON?: string;
  DECISION: 'APPROVE' | 'REJECT';
  END_DATE?: string;
  START_DATE?: string;
  EMPLOYEE_NAME: string;
}

/** Form: VACATION_HR_REVIEW (v1) */
export interface VacationHrReviewOutput extends Record<string, unknown> {
  DAYS: number;
  NOTES?: string;
  REASON?: string;
  DECISION: 'APPROVE' | 'REJECT';
  EMPLOYEE_NAME: string;
  MANAGER_DECISION?: string;
}

// ---------------------------------------------------------------------------
// Process definition
// ---------------------------------------------------------------------------

export const vacationLeaveRequestProcess = defineProcess('Vacation Leave Request', {
  taskQueue: 'flowstile',
  // Case plan: MANAGER_REVIEW → HR_REVIEW → LEDGER_UPDATE
  plan: ['MANAGER_REVIEW', 'HR_REVIEW', 'LEDGER_UPDATE'],
}, (task) => ({
  vacationManagerReview: task<VacationManagerReviewOutput>('VACATION_MANAGER_REVIEW', { phase: 'MANAGER_REVIEW', defaults: { priority: 'high' } }),
  vacationHrReview: task<VacationHrReviewOutput>('VACATION_HR_REVIEW', { phase: 'HR_REVIEW' }),
}));
