// Generated by flowstile codegen — do not edit manually.
// Source: http://localhost:3000  |  Process: Order Fulfillment  |  2026-05-30
// Regenerate: flowstile-codegen --process "Order Fulfillment" --task-queue flowstile

import { defineProcess } from '@flowstile/sdk/process';

// ---------------------------------------------------------------------------
// Form output types (typed submission data returned by createAndWait)
// ---------------------------------------------------------------------------

/** Form: approve-order (v1) */
export interface ApproveOrderOutput extends Record<string, unknown> {
  CUSTOMER_NAME: string;
  ORDER_ID: string;
  ORDER_ITEMS: Array<{ name?: string; quantity?: number; price?: number; }>;
  TOTAL: number;
  DECISION: 'APPROVED' | 'REJECTED';
  REASON?: string;
}

/** Form: confirm-shipment (v1) */
export interface ConfirmShipmentOutput extends Record<string, unknown> {
  ORDER_ID: string;
  CUSTOMER_NAME: string;
  ORDER_ITEMS: Array<{ name?: string; quantity?: number; price?: number; }>;
  SHIPPING_ADDRESS: string;
  DECISION: 'CONFIRMED' | 'REJECTED';
  REASON: string;
  TRACKING_NUMBER?: string;
}

/** Form: handle-exception (v1) */
export interface HandleExceptionOutput extends Record<string, unknown> {
  ORDER_ID: string;
  REASON: string;
  REFUNDED: boolean;
  RESOLUTION: string;
  NOTES?: string;
}

// ---------------------------------------------------------------------------
// Process definition
// ---------------------------------------------------------------------------

export const orderFulfillmentProcess = defineProcess('Order Fulfillment', {
  taskQueue: 'flowstile',
  // Case plan: APPROVAL → PAYMENT → SHIPMENT (PAYMENT is fully automated — no
  // human tasks; the stepper jumps it to achieved when shipment starts).
  plan: ['APPROVAL', 'PAYMENT', 'SHIPMENT'],
}, (task) => ({
  approveOrder: task<ApproveOrderOutput>('APPROVE_ORDER', { phase: 'APPROVAL', defaults: { priority: 'high' } }),
  confirmShipment: task<ConfirmShipmentOutput>('CONFIRM_SHIPMENT', { phase: 'SHIPMENT' }),
  handleException: task<HandleExceptionOutput>('HANDLE_EXCEPTION', { phase: null, defaults: { priority: 'urgent' } }),
}));
