// Generated by flowstile codegen — do not edit manually.
// Source: http://localhost:3000  |  Process: Order Fulfillment  |  2026-05-30
// Regenerate: flowstile-codegen --process "Order Fulfillment" --task-queue flowstile

import { defineProcess, defineTask } from '@flowstile/sdk/process';

// ---------------------------------------------------------------------------
// Form output types (typed submission data returned by createAndWait)
// ---------------------------------------------------------------------------

/** Form: approve-order (v1) */
export interface ApproveOrderOutput extends Record<string, unknown> {
  CUSTOMER_NAME: string;
  ORDER_ID: string;
  ORDER_ITEMS: Array<{ name?: string; quantity?: number; price?: number; }>;
  TOTAL: number;
  DECISION: 'APPROVED' | 'REJECTED';
  REASON?: string;
}

/** Form: confirm-shipment (v1) */
export interface ConfirmShipmentOutput extends Record<string, unknown> {
  ORDER_ID: string;
  CUSTOMER_NAME: string;
  ORDER_ITEMS: Array<{ name?: string; quantity?: number; price?: number; }>;
  SHIPPING_ADDRESS: string;
  DECISION: 'CONFIRMED' | 'REJECTED';
  REASON: string;
  TRACKING_NUMBER?: string;
}

/** Form: handle-exception (v1) */
export interface HandleExceptionOutput extends Record<string, unknown> {
  ORDER_ID: string;
  REASON: string;
  REFUNDED: boolean;
  RESOLUTION: string;
  NOTES?: string;
}

// ---------------------------------------------------------------------------
// Process definition
// ---------------------------------------------------------------------------

export const orderFulfillmentProcess = defineProcess('Order Fulfillment', {
  taskQueue: 'flowstile',
  tasks: {
    approveOrder: defineTask<ApproveOrderOutput>('APPROVE_ORDER', { priority: 'high' }),
    confirmShipment: defineTask<ConfirmShipmentOutput>('CONFIRM_SHIPMENT'),
    handleException: defineTask<HandleExceptionOutput>('HANDLE_EXCEPTION', { priority: 'urgent' }),
  },
});
