// Generated by flowstile codegen — do not edit manually.
// Source: http://localhost:3000  |  Process: Expense Approval  |  2026-06-14
// Regenerate: flowstile-codegen --process "Expense Approval" --task-queue flowstile

import { defineProcess } from '@flowstile/sdk/process';

// ---------------------------------------------------------------------------
// Form output types (typed submission data returned by createAndWait)
// ---------------------------------------------------------------------------

/** Form: EXPENSE_MANAGER_REVIEW (v1) */
export interface ExpenseManagerReviewOutput extends Record<string, unknown> {
  NOTES?: string;
  AMOUNT: number;
  CATEGORY: 'TRAVEL' | 'MEALS' | 'EQUIPMENT' | 'OTHER';
  DECISION: 'APPROVE' | 'REJECT';
  DESCRIPTION?: string;
  EMPLOYEE_NAME: string;
}

/** Form: EXPENSE_FINANCE_REVIEW (v1) */
export interface ExpenseFinanceReviewOutput extends Record<string, unknown> {
  NOTES?: string;
  AMOUNT: number;
  CATEGORY: 'TRAVEL' | 'MEALS' | 'EQUIPMENT' | 'OTHER';
  DECISION: 'APPROVE' | 'REJECT';
  EMPLOYEE_NAME: string;
  MANAGER_DECISION?: string;
}

// ---------------------------------------------------------------------------
// Process definition
// ---------------------------------------------------------------------------

export const expenseApprovalProcess = defineProcess('Expense Approval', {
  taskQueue: 'flowstile',
  // Case plan: MANAGER_REVIEW → FINANCE_REVIEW → REIMBURSEMENT
  plan: ['MANAGER_REVIEW', 'FINANCE_REVIEW', 'REIMBURSEMENT'],
}, (task) => ({
  expenseManagerReview: task<ExpenseManagerReviewOutput>('EXPENSE_MANAGER_REVIEW', { phase: 'MANAGER_REVIEW', defaults: { priority: 'high' } }),
  expenseFinanceReview: task<ExpenseFinanceReviewOutput>('EXPENSE_FINANCE_REVIEW', { phase: 'FINANCE_REVIEW' }),
}));
