// Generated by flowstile codegen — do not edit manually.
// Source: http://localhost:3000  |  Process: Loan Origination  |  2026-06-11
// Regenerate: flowstile-codegen --process "Loan Origination" --task-queue flowstile

import { defineProcess } from '@flowstile/sdk/process';

// ---------------------------------------------------------------------------
// Form output types (typed submission data returned by createAndWait)
// ---------------------------------------------------------------------------

/** Form: LOAN_APPLICATION_REVIEW (v1) */
export interface LoanReviewApplicationOutput extends Record<string, unknown> {
  NOTES?: string;
  AMOUNT: number;
  PURPOSE?: string;
  DECISION: 'PROCEED' | 'REJECT';
  CUSTOMER_NAME: string;
  REWORK_REASON?: string;
}

/** Form: LOAN_RISK_ASSESSMENT (v1) */
export interface LoanAssessRiskOutput extends Record<string, unknown> {
  AMOUNT: number;
  DECISION: 'APPROVE' | 'REJECT' | 'SEND_BACK';
  RATIONALE: string;
  CREDIT_SCORE: number;
  CUSTOMER_NAME: string;
}

/** Form: LOAN_SENIOR_REVIEW (v1) */
export interface LoanSeniorReviewOutput extends Record<string, unknown> {
  AMOUNT: number;
  COMMENT?: string;
  DECISION: 'ENDORSE' | 'REJECT';
  CREDIT_SCORE: number;
  RISK_RATIONALE?: string;
}

/** Form: LOAN_FINAL_DECISION (v1) */
export interface LoanFinalDecisionOutput extends Record<string, unknown> {
  APR?: number;
  TERMS?: string;
  AMOUNT: number;
  DECISION: 'APPROVED' | 'DECLINED';
  CREDIT_SCORE?: number;
  CUSTOMER_NAME: string;
}

// ---------------------------------------------------------------------------
// Process definition
// ---------------------------------------------------------------------------

export const loanOriginationProcess = defineProcess('Loan Origination', {
  taskQueue: 'flowstile',
  // Case plan: APPLICATION_REVIEW → CREDIT_ASSESSMENT → UNDERWRITING → FINAL_DECISION
  plan: ['APPLICATION_REVIEW', 'CREDIT_ASSESSMENT', 'UNDERWRITING', 'FINAL_DECISION'],
}, (task) => ({
  loanReviewApplication: task<LoanReviewApplicationOutput>('LOAN_REVIEW_APPLICATION', { phase: 'APPLICATION_REVIEW', defaults: { priority: 'high' } }),
  loanAssessRisk: task<LoanAssessRiskOutput>('LOAN_ASSESS_RISK', { phase: 'UNDERWRITING' }),
  loanSeniorReview: task<LoanSeniorReviewOutput>('LOAN_SENIOR_REVIEW', { phase: 'UNDERWRITING', defaults: { priority: 'high' } }),
  loanFinalDecision: task<LoanFinalDecisionOutput>('LOAN_FINAL_DECISION', { phase: 'FINAL_DECISION' }),
}));
