"""Generate typed pydantic models from a process's published form schemas.

A thin wrapper over `datamodel-code-generator` (the standard JSON Schema → pydantic
tool). It fetches each form's `jsonSchema` from a live Flowstile server and emits
one ``BaseModel`` per form, named ``<FormCode>Output``, ready to pass as
``output=`` to ``create_task_and_wait`` — keeping the typed models mechanically
faithful to the server instead of hand-maintained (which drifts).

Build-time only. Install the extra and run the CLI:

    pip install 'flowstile[codegen]'
    flowstile-codegen --process "Loan Origination" --api-key fsk_... --out loan_models.py
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .client import FlowstileClient

_ROOT_TITLE = "GeneratedFormsRoot"


def class_name_for(form_code: str) -> str:
    """`LOAN_APPLICATION_REVIEW` → `LoanApplicationReviewOutput`."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", form_code) if p]
    return "".join(p.capitalize() for p in parts) + "Output"


def render_models(forms: list[tuple[str, dict[str, Any]]], *, regenerate_cmd: str) -> str:
    """Render pydantic source for ``[(class_name, json_schema), ...]``.

    datamodel-code-generator is imported lazily so the runtime SDK never needs it.
    """
    try:
        from datamodel_code_generator import (  # type: ignore[import-untyped]
            DataModelType,
            InputFileType,
            LiteralType,
            generate,
        )
        from datamodel_code_generator.format import Formatter  # type: ignore[import-untyped]
    except ImportError as err:  # pragma: no cover - exercised via the CLI
        raise RuntimeError(
            "flowstile-codegen requires the 'codegen' extra: pip install 'flowstile[codegen]'"
        ) from err

    # One schema with every form under $defs → one model per form, names = $def keys.
    combined = {"title": _ROOT_TITLE, "type": "object", "$defs": dict(forms)}
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "models.py"
        generate(
            json.dumps(combined),
            input_file_type=InputFileType.JsonSchema,
            output=out,
            output_model_type=DataModelType.PydanticV2BaseModel,
            enum_field_as_literal=LiteralType.All,  # inline Literal[...] instead of Enum classes
            formatters=[Formatter.BLACK, Formatter.ISORT],
            use_double_quotes=True,
        )
        text = out.read_text()

    # Replace datamodel-codegen's timestamped header (non-deterministic) with ours.
    text = re.sub(r"\A(#[^\n]*\n)+\n?", "", text)
    # Drop the empty root wrapper model (datamodel-codegen mangles the title, so
    # match any field-less BaseModel — real form models always have fields).
    text = re.sub(r"\n*class \w+\(BaseModel\):\n    pass\n", "\n", text)

    header = (
        "# Generated by flowstile-codegen — do not edit by hand.\n"
        f"# Regenerate: {regenerate_cmd}\n\n"
    )
    return header + text.lstrip("\n")


async def collect_forms(
    client: FlowstileClient, process_name: str
) -> list[tuple[str, dict[str, Any]]]:
    """Fetch a process's task definitions and each one's published form schema."""
    procs = await client.request("GET", "/processes?limit=200")
    proc = next((p for p in procs["items"] if p["name"] == process_name), None)
    if proc is None:
        raise RuntimeError(f"process {process_name!r} not found")

    tasks = await client.request("GET", f"/processes/{proc['id']}/tasks")
    forms: list[tuple[str, dict[str, Any]]] = []
    seen: set[str] = set()
    for task in tasks["items"]:
        code = task.get("formDefinitionCode")
        if not code or code in seen:
            continue
        seen.add(code)
        form = await client.request("GET", f"/forms/{code}")
        forms.append((class_name_for(code), form["jsonSchema"]))
    return forms


async def _run(process: str, out: str, base_url: str, api_key: str | None) -> None:
    client = FlowstileClient(base_url, api_key=api_key)
    try:
        forms = await collect_forms(client, process)
    finally:
        await client.aclose()
    if not forms:
        raise SystemExit(f"No published forms found for process {process!r}")
    cmd = f'flowstile-codegen --process "{process}" --out {out}'
    Path(out).write_text(render_models(forms, regenerate_cmd=cmd))
    print(f"Wrote {len(forms)} model(s) to {out}: {', '.join(n for n, _ in forms)}")


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="flowstile-codegen",
        description="Generate pydantic models from a Flowstile process's form schemas.",
    )
    parser.add_argument("--process", required=True, help="Process name")
    parser.add_argument("--out", required=True, help="Output .py file")
    parser.add_argument("--base-url", default=os.environ.get("FLOWSTILE_SERVER_URL", "http://localhost:3000"))
    parser.add_argument("--api-key", default=os.environ.get("FLOWSTILE_API_KEY"), help="Service API key")
    args = parser.parse_args()
    asyncio.run(_run(args.process, args.out, args.base_url, args.api_key))
