"""Generate typed pydantic models from a process's published form schemas.

A thin wrapper over `datamodel-code-generator` (the standard JSON Schema → pydantic
tool). It fetches each form's `jsonSchema` from a live Flowstile server and emits
one ``BaseModel`` per form, named ``<FormCode>Output``, ready to pass as
``output=`` to ``create_task_and_wait`` — keeping the typed models mechanically
faithful to the server instead of hand-maintained (which drifts).

Build-time only. Install the extra and run the CLI:

    pip install 'flowstile[codegen]'
    flowstile-codegen --process "Loan Origination" --api-key fsk_... --out loan_models.py
"""

from __future__ import annotations

import argparse
import asyncio
import json
import os
import re
import tempfile
from pathlib import Path
from typing import Any

from .client import FlowstileClient

_ROOT_TITLE = "GeneratedFormsRoot"


def class_name_for(form_code: str) -> str:
    """`LOAN_APPLICATION_REVIEW` → `LoanApplicationReviewOutput`."""
    parts = [p for p in re.split(r"[^A-Za-z0-9]+", form_code) if p]
    return "".join(p.capitalize() for p in parts) + "Output"


def render_models(forms: list[tuple[str, dict[str, Any]]], *, regenerate_cmd: str) -> str:
    """Render pydantic source for ``[(class_name, json_schema), ...]``.

    datamodel-code-generator is imported lazily so the runtime SDK never needs it.
    """
    try:
        from datamodel_code_generator import (  # type: ignore[import-untyped]
            DataModelType,
            InputFileType,
            LiteralType,
            generate,
        )
        from datamodel_code_generator.format import Formatter  # type: ignore[import-untyped]
    except ImportError as err:  # pragma: no cover - exercised via the CLI
        raise RuntimeError(
            "flowstile-codegen requires the 'codegen' extra: pip install 'flowstile[codegen]'"
        ) from err

    # One schema with every form under $defs → one model per form, names = $def keys.
    combined = {"title": _ROOT_TITLE, "type": "object", "$defs": dict(forms)}
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "models.py"
        generate(
            json.dumps(combined),
            input_file_type=InputFileType.JsonSchema,
            output=out,
            output_model_type=DataModelType.PydanticV2BaseModel,
            enum_field_as_literal=LiteralType.All,  # inline Literal[...] instead of Enum classes
            formatters=[Formatter.BLACK, Formatter.ISORT],
            use_double_quotes=True,
        )
        text = out.read_text()

    # Replace datamodel-codegen's timestamped header (non-deterministic) with ours.
    text = re.sub(r"\A(#[^\n]*\n)+\n?", "", text)
    # Drop the empty root wrapper model (datamodel-codegen mangles the title, so
    # match any field-less BaseModel — real form models always have fields).
    text = re.sub(r"\n*class \w+\(BaseModel\):\n    pass\n", "\n", text)

    header = (
        "# Generated by flowstile-codegen — do not edit by hand.\n"
        f"# Regenerate: {regenerate_cmd}\n\n"
    )
    return header + text.lstrip("\n")


def render(
    tasks: list[tuple[str, str]],
    form_models: list[tuple[str, dict[str, Any]]],
    *,
    regenerate_cmd: str,
) -> str:
    """Render the full module: one model per form + a FlowstileTask descriptor
    per task (binding the task code to its model so they can't be mismatched).

    `tasks` is ``[(task_code, class_name), ...]``; `form_models` is the unique
    ``[(class_name, json_schema), ...]``.
    """
    source = render_models(form_models, regenerate_cmd=regenerate_cmd)
    if not tasks:
        return source
    # Put the FlowstileTask import in the import block (not before the descriptors
    # at the bottom) so the generated file is import-order/E402 clean.
    import_line = "from flowstile import FlowstileTask"
    if "\nfrom pydantic import" in source:
        source = source.replace("\nfrom pydantic import", f"\n{import_line}\nfrom pydantic import", 1)
    else:  # no models emitted an import — fall back to before the first class
        source = source.replace("\n\nclass ", f"\n\n{import_line}\n\nclass ", 1)
    lines = ["", "# Task descriptors — bind each task code to its form-output model."]
    for task_code, class_name in tasks:
        lines.append(f'{task_code} = FlowstileTask("{task_code}", output={class_name})')
    return source.rstrip() + "\n\n\n" + "\n".join(lines) + "\n"


async def collect_process(
    client: FlowstileClient, process_name: str
) -> tuple[list[tuple[str, str]], list[tuple[str, dict[str, Any]]]]:
    """Fetch a process's tasks and forms.

    Returns ``(tasks, form_models)`` where tasks is ``[(task_code, class_name)]``
    and form_models is the unique ``[(class_name, json_schema)]``.
    """
    procs = await client.request("GET", "/processes?limit=200")
    proc = next((p for p in procs["items"] if p["name"] == process_name), None)
    if proc is None:
        raise RuntimeError(f"process {process_name!r} not found")

    task_defs = await client.request("GET", f"/processes/{proc['id']}/tasks")
    tasks: list[tuple[str, str]] = []
    form_models: list[tuple[str, dict[str, Any]]] = []
    seen_forms: set[str] = set()
    for task in task_defs["items"]:
        form_code = task.get("formDefinitionCode")
        if not form_code:
            continue
        class_name = class_name_for(form_code)
        if form_code not in seen_forms:
            seen_forms.add(form_code)
            form = await client.request("GET", f"/forms/{form_code}")
            form_models.append((class_name, form["jsonSchema"]))
        tasks.append((task["code"], class_name))
    return tasks, form_models


async def _run(process: str, out: str, base_url: str, api_key: str | None, check: bool) -> None:
    client = FlowstileClient(base_url, api_key=api_key)
    try:
        tasks, form_models = await collect_process(client, process)
    finally:
        await client.aclose()
    if not form_models:
        raise SystemExit(f"No published forms found for process {process!r}")

    cmd = f'flowstile-codegen --process "{process}" --out {out}'
    rendered = render(tasks, form_models, regenerate_cmd=cmd)

    if check:
        # Drift guard for CI: fail if the committed file is missing or stale.
        current = Path(out).read_text() if Path(out).exists() else None
        if current == rendered:
            print(f"{out} is up to date.")
            return
        print(f"::error:: {out} is out of date — regenerate with: {cmd}")
        raise SystemExit(1)

    Path(out).write_text(rendered)
    print(
        f"Wrote {len(form_models)} model(s) and {len(tasks)} descriptor(s) to {out}: "
        f"{', '.join(c for c, _ in form_models)}"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        prog="flowstile-codegen",
        description="Generate typed pydantic models + task descriptors from a Flowstile process.",
    )
    parser.add_argument("--process", required=True, help="Process name")
    parser.add_argument("--out", required=True, help="Output .py file")
    parser.add_argument("--base-url", default=os.environ.get("FLOWSTILE_SERVER_URL", "http://localhost:3000"))
    parser.add_argument("--api-key", default=os.environ.get("FLOWSTILE_API_KEY"), help="Service API key")
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if --out is missing or out of date, without writing (for CI).",
    )
    args = parser.parse_args()
    asyncio.run(_run(args.process, args.out, args.base_url, args.api_key, args.check))
