// Generated by flowstile codegen — do not edit manually.
// Source: http://localhost:3000  |  Process: Purchase Requisition Approval  |  2026-06-14
// Regenerate: flowstile-codegen --process "Purchase Requisition Approval" --task-queue flowstile

import { defineProcess } from '@flowstile/sdk/process';

// ---------------------------------------------------------------------------
// Form output types (typed submission data returned by createAndWait)
// ---------------------------------------------------------------------------

/** Form: PR_MANAGER_APPROVAL_FORM (v1) */
export interface PrManagerApprovalOutput extends Record<string, unknown> {
  ITEM: string;
  NOTES?: string;
  AMOUNT: number;
  DECISION: 'APPROVED' | 'REJECTED';
  JUSTIFICATION?: string;
  REQUESTER_NAME: string;
}

/** Form: PR_FINANCE_APPROVAL_FORM (v1) */
export interface PrFinanceApprovalOutput extends Record<string, unknown> {
  ITEM: string;
  NOTES?: string;
  AMOUNT: number;
  DECISION: 'APPROVED' | 'REJECTED';
  JUSTIFICATION?: string;
  REQUESTER_NAME: string;
  MANAGER_DECISION?: string;
}

// ---------------------------------------------------------------------------
// Process definition
// ---------------------------------------------------------------------------

export const purchaseRequisitionApprovalProcess = defineProcess('Purchase Requisition Approval', {
  taskQueue: 'flowstile',
  // Case plan: MANAGER_APPROVAL → FINANCE_APPROVAL → PO_ISSUANCE
  plan: ['MANAGER_APPROVAL', 'FINANCE_APPROVAL', 'PO_ISSUANCE'],
}, (task) => ({
  prManagerApproval: task<PrManagerApprovalOutput>('PR_MANAGER_APPROVAL', { phase: 'MANAGER_APPROVAL', defaults: { priority: 'high' } }),
  prFinanceApproval: task<PrFinanceApprovalOutput>('PR_FINANCE_APPROVAL', { phase: 'FINANCE_APPROVAL' }),
}));
