"""Unit tests for the codegen wrapper over datamodel-code-generator."""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

from flowstile.codegen import class_name_for, render_models


def test_class_name_for() -> None:
    assert class_name_for("LOAN_APPLICATION_REVIEW") == "LoanApplicationReviewOutput"
    assert class_name_for("REVIEW_LOAN") == "ReviewLoanOutput"


def test_render_models_emits_typed_models() -> None:
    forms = [
        (
            "ManagerReviewOutput",
            {
                "type": "object",
                "properties": {
                    "DECISION": {"type": "string", "enum": ["APPROVE", "REJECT"]},
                    "NOTES": {"type": "string"},
                    "AMOUNT": {"type": "number"},
                },
                "required": ["DECISION", "AMOUNT"],
            },
        ),
        (
            "PayoutOutput",
            {
                "type": "object",
                "properties": {"REFERENCE": {"type": "string"}},
                "required": ["REFERENCE"],
            },
        ),
    ]
    src = render_models(forms, regenerate_cmd='flowstile-codegen --process "X" --out m.py')

    assert src.startswith("# Generated by flowstile-codegen")
    assert "Regenerate: flowstile-codegen" in src
    # One model per form, inline Literal, required vs optional.
    assert "class ManagerReviewOutput(BaseModel):" in src
    assert 'DECISION: Literal["APPROVE", "REJECT"]' in src
    assert "NOTES: str | None = None" in src
    assert "AMOUNT: float" in src and "AMOUNT: float | None" not in src
    assert "class PayoutOutput(BaseModel):" in src
    # No empty root wrapper, no datamodel-codegen timestamp header.
    assert "    pass\n" not in src
    assert "datamodel-codegen" not in src


def test_rendered_models_import_and_validate(tmp_path: Path) -> None:
    forms = [
        (
            "ReviewOutput",
            {
                "type": "object",
                "properties": {"DECISION": {"type": "string", "enum": ["APPROVE", "REJECT"]}},
                "required": ["DECISION"],
            },
        )
    ]
    out = tmp_path / "gen_models.py"
    out.write_text(render_models(forms, regenerate_cmd="flowstile-codegen ..."))

    spec = importlib.util.spec_from_file_location("gen_models_test", out)
    assert spec and spec.loader
    mod = importlib.util.module_from_spec(spec)
    sys.modules["gen_models_test"] = mod  # register so forward refs resolve
    try:
        spec.loader.exec_module(mod)
        instance = mod.ReviewOutput.model_validate({"DECISION": "APPROVE"})
        assert instance.DECISION == "APPROVE"
    finally:
        sys.modules.pop("gen_models_test", None)
